import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { FolderPlus, FileText, Layers, Trash2, Sparkles } from "lucide-react";
import { createCollection, deleteCollection } from "@/lib/collections.functions";
import { useActiveCollection } from "@/hooks/use-active-collection";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";
import { triggerHaptic } from "@/lib/haptics";

export const Route = createFileRoute("/_authenticated/app/")({
  head: () => ({
    meta: [
      { title: "Workspace — Knowra" },
      { name: "description", content: "Your Knowra collections and knowledge base overview." },
      { property: "og:title", content: "Workspace — Knowra" },
      { property: "og:description", content: "Your Knowra collections and knowledge base overview." },
    ],
  }),
  component: Overview,
});

function Overview() {
  const { collections, isLoading, setActiveId, activeId } = useActiveCollection();
  const [name, setName] = useState("");
  const queryClient = useQueryClient();

  const create = useMutation({
    mutationFn: (value: string) => createCollection({ data: { name: value } }),
    onSuccess: (collection) => {
      setName("");
      triggerHaptic("success");
      setActiveId(collection.id);
      void queryClient.invalidateQueries({ queryKey: ["collections"] });
    },
    onError: (e: Error) => toast.error(e.message),
  });

  const remove = useMutation({
    mutationFn: (id: string) => deleteCollection({ data: { id } }),
    onSuccess: () => {
      toast.success("Collection deleted");
      void queryClient.invalidateQueries({ queryKey: ["collections"] });
    },
    onError: (e: Error) => toast.error(e.message),
  });

  return (
    <div className="mx-auto max-w-5xl py-4 sm:py-6">
      <div className="inline-flex items-center gap-2 rounded-full border border-neutral-300 bg-white px-4 py-1.5 text-xs font-bold tracking-widest text-[#ff4500] uppercase shadow-sm font-['Chakra_Petch',sans-serif] mb-3">
        <span>Knowledge Base Repositories</span>
      </div>

      <h1 className="font-['Orbitron',sans-serif] text-3xl sm:text-4xl font-black text-neutral-950 tracking-tight">
        Knowledge Collections
      </h1>
      <p className="mt-2 text-sm text-neutral-600 max-w-2xl leading-relaxed">
        Isolated evidence repositories. Answers generated by Knowra are strictly grounded in the active collection selected.
      </p>

      <form
        className="mt-6 flex flex-col gap-3 sm:flex-row bg-white border border-neutral-200 p-3 rounded-2xl shadow-sm"
        onSubmit={(e) => {
          e.preventDefault();
          if (name.trim().length > 0) create.mutate(name.trim());
        }}
      >
        <Input
          value={name}
          onChange={(e) => setName(e.target.value)}
          placeholder="New collection name (e.g., Financial Audits 2026)"
          maxLength={80}
          className="h-12 rounded-xl bg-neutral-50 border-neutral-200 font-mono text-xs focus:bg-white"
          aria-label="New collection name"
        />
        <Button
          type="submit"
          disabled={create.isPending || name.trim().length === 0}
          className="h-12 rounded-xl bg-neutral-950 hover:bg-neutral-800 text-white font-['Chakra_Petch',sans-serif] font-bold tracking-wider uppercase px-6"
        >
          <FolderPlus className="size-4 text-[#ff4500] mr-2" /> Create Collection
        </Button>
      </form>

      <div className="mt-8 grid gap-4 sm:grid-cols-2">
        {isLoading && <p className="text-neutral-500 font-mono text-xs">Loading collections database…</p>}
        {!isLoading && collections.length === 0 && (
          <p className="text-neutral-500 font-mono text-xs">
            No collections created yet. Enter a collection name above to create your first grounded knowledge repository.
          </p>
        )}
        {collections.map((c) => (
          <div
            key={c.id}
            className={`rounded-3xl border p-6 shadow-lg transition-all flex flex-col justify-between ${
              activeId === c.id
                ? "bg-neutral-950 text-white border-neutral-950 ring-2 ring-[#ff4500]"
                : "bg-white border-neutral-200 text-neutral-900 hover:border-neutral-300"
            }`}
          >
            <div>
              <div className="flex items-start justify-between gap-3">
                <div className="min-w-0">
                  <h3 className={`font-['Orbitron',sans-serif] text-lg font-bold truncate ${activeId === c.id ? "text-white" : "text-neutral-950"}`}>
                    {c.name}
                  </h3>
                  <div className="mt-2 flex flex-wrap gap-2 text-xs font-mono">
                    <span className={`px-2.5 py-1 rounded-full ${activeId === c.id ? "bg-white/10 text-white" : "bg-neutral-100 text-neutral-700"}`}>
                      <FileText className="size-3 inline mr-1 text-[#ff4500]" /> {c.documentCount} docs
                    </span>
                    <span className={`px-2.5 py-1 rounded-full ${activeId === c.id ? "bg-white/10 text-white" : "bg-neutral-100 text-neutral-700"}`}>
                      <Layers className="size-3 inline mr-1 text-emerald-400" /> {c.chunkCount} vectors
                    </span>
                  </div>
                </div>
                <Button
                  variant="ghost"
                  size="sm"
                  aria-label={`Delete ${c.name}`}
                  onClick={() => remove.mutate(c.id)}
                  className={`rounded-full hover:bg-red-500/20 ${activeId === c.id ? "text-neutral-400 hover:text-white" : "text-neutral-400 hover:text-red-600"}`}
                >
                  <Trash2 className="size-4" />
                </Button>
              </div>
            </div>

            <div className="mt-6 pt-4 border-t border-current/10 flex flex-wrap gap-2">
              <Button
                variant={activeId === c.id ? "default" : "outline"}
                size="sm"
                className={`h-9 rounded-full text-xs font-bold font-['Chakra_Petch',sans-serif] tracking-wider uppercase ${
                  activeId === c.id
                    ? "bg-[#ff4500] hover:bg-[#e03d00] text-white shadow-md shadow-[#ff4500]/30"
                    : "border-neutral-300 bg-white text-neutral-900 hover:bg-neutral-100"
                }`}
                onClick={() => setActiveId(c.id)}
              >
                {activeId === c.id ? "Active Repository" : "Set Active"}
              </Button>
              <Button asChild size="sm" variant="ghost" className={`h-9 rounded-full text-xs font-semibold ${activeId === c.id ? "text-white hover:bg-white/10" : "text-neutral-700 hover:bg-neutral-100"}`}>
                <Link to="/app/documents" onClick={() => setActiveId(c.id)}>
                  Documents →
                </Link>
              </Button>
              <Button asChild size="sm" variant="ghost" className={`h-9 rounded-full text-xs font-semibold ${activeId === c.id ? "text-white hover:bg-white/10" : "text-neutral-700 hover:bg-neutral-100"}`}>
                <Link to="/app/ask" onClick={() => setActiveId(c.id)}>
                  Ask Knowra →
                </Link>
              </Button>
            </div>
          </div>
        ))}
      </div>

      {/* HOW IT WORKS & KEY USE CASES SECTION */}
      <div className="mt-12 rounded-3xl bg-neutral-950 text-white p-8 shadow-2xl space-y-6">
        <div className="flex items-center gap-2 text-xs font-mono text-[#ff4500] font-bold uppercase tracking-widest">
          <Sparkles className="size-4 animate-pulse text-[#ff4500]" /> SYSTEM ARCHITECTURE & GOVERNING RAG PIPELINE
        </div>

        <h2 className="font-['Orbitron',sans-serif] text-2xl font-bold">How Knowledge Collections Work</h2>

        <div className="grid gap-6 md:grid-cols-3">
          <div className="rounded-2xl border border-white/10 bg-neutral-900 p-5 space-y-2">
            <span className="font-mono text-xs text-[#ff4500] font-bold">01 / ISOLATED BOUNDARIES</span>
            <h4 className="font-['Space_Grotesk',sans-serif] font-bold text-base text-white">Strict Multi-Tenant Grounding</h4>
            <p className="text-xs text-neutral-400 leading-relaxed">
              Every collection acts as a sandboxed vector database. RAG queries never retrieve context from outside the active collection.
            </p>
          </div>

          <div className="rounded-2xl border border-white/10 bg-neutral-900 p-5 space-y-2">
            <span className="font-mono text-xs text-[#ff4500] font-bold">02 / HYBRID SEARCH</span>
            <h4 className="font-['Space_Grotesk',sans-serif] font-bold text-base text-white">3072D Dense + BM25 Keywords</h4>
            <p className="text-xs text-neutral-400 leading-relaxed">
              pgvector embeddings combine with BM25 keyword matching and cross-encoder reranking before prompt generation.
            </p>
          </div>

          <div className="rounded-2xl border border-white/10 bg-neutral-900 p-5 space-y-2">
            <span className="font-mono text-xs text-[#ff4500] font-bold">03 / VERBATIM CITATIONS</span>
            <h4 className="font-['Space_Grotesk',sans-serif] font-bold text-base text-white">100% Traceable Claims</h4>
            <p className="text-xs text-neutral-400 leading-relaxed">
              Outputs link directly to source documents, page numbers, and verbatim passage excerpts so no claims are assumed.
            </p>
          </div>
        </div>

        <div className="pt-6 border-t border-white/10">
          <h3 className="font-['Orbitron',sans-serif] text-lg font-bold mb-4">Enterprise Use Cases</h3>
          <div className="grid gap-4 sm:grid-cols-2">
            <div className="p-4 rounded-xl bg-black/40 border border-white/5 text-xs font-mono space-y-1">
              <span className="text-emerald-400 font-bold">Finance & Auditing</span>
              <p className="text-neutral-300">Upload SEC 10-K filings, Q1-Q4 balance sheets, and audit reports for instant metric verification.</p>
            </div>
            <div className="p-4 rounded-xl bg-black/40 border border-white/5 text-xs font-mono space-y-1">
              <span className="text-[#ff4500] font-bold">Legal & Contracts</span>
              <p className="text-neutral-300">Compare MSAs, NDAs, and service agreements to flag conflicting terms across documents.</p>
            </div>
            <div className="p-4 rounded-xl bg-black/40 border border-white/5 text-xs font-mono space-y-1">
              <span className="text-sky-400 font-bold">Engineering & Architecture</span>
              <p className="text-neutral-300">Ingest technical specs, API documentations, and topology diagrams for accurate developer Q&A.</p>
            </div>
            <div className="p-4 rounded-xl bg-black/40 border border-white/5 text-xs font-mono space-y-1">
              <span className="text-amber-400 font-bold">Academic & Research</span>
              <p className="text-neutral-300">Synthesize research papers and literature reviews backed by verbatim page citations.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
